In [17]:
#Defining parent class Employee
class Employee():

  #Class variables to keep track of instances
  employee_count = 0
  employee_salary = 0

  #Constructor used to initialize values for the objects
  def __init__(self, name, family, department, salary = 0):
    self.name = name
    self.family = family
    self.salary = salary
    self.department = department

    Employee.employee_count += 1
    Employee.employee_salary += self.salary

  #Method that gives average salary for the employees
  def average_salary(self):
    return "The Average Salary of all Employees is: $" + str(Employee.employee_salary / Employee.employee_count)


#Defining child another class and inheriting the properties of parent class
class Full_Time_Employee(Employee):

  #class variables that keeps track of instances
  full_employee_salary = 0
  full_employee_count = 0

  #Constructor used to initialize values for the object variables inherited from the parent class
  def __init__(self, name, family, department,  salary):
    super().__init__(name, family, department)
    self.salary = salary

    Full_Time_Employee.full_employee_count += 1
    Full_Time_Employee.full_employee_salary += self.salary

  #Method that overries the parent class method to give average salary for the full time employees
  def average_salary(self):
      return "The Average Salary of all Full time Employees is: $" + str(Full_Time_Employee.full_employee_salary / Full_Time_Employee.full_employee_count)



#Defining objects for the parent class
employee_1 = Employee("Sudhir", "Sai_charan", "Software Developement", 12000)
employee_2 = Employee("Harshitha", "priya", "Salesforce", 14000)




#Defining objects for the child class
full_employee_1 = Full_Time_Employee("kiran", "Reddy", "Research Scientist in ML", 20000)
full_employee_2 = Full_Time_Employee("Zubir", "Khan", "Marketing", 13000)

#Printing total no of employess and full time employees defined
print("Total no. of employees in the company are: " + str(Employee.employee_count))
print("Total no. of full time employees in the company are: " + str(Full_Time_Employee.full_employee_count))

print()

#Printing average salaries of employess and full time employees
print(employee_1.average_salary())
print(full_employee_1.average_salary())





Total no. of employees in the company are: 4
Total no. of full time employees in the company are: 2

The Average Salary of all Employees is: $6500.0
The Average Salary of all Full time Employees is: $16500.0


In [18]:
#Importing Numpy module as np
import numpy as np

#Creating random vector of size 20 containing floating values in the range 1-20
random_vec = np.arange(1, 21, dtype=float)
print(random_vec)

#Reshaping the size of the vector to an array
random_vec = random_vec.reshape(4,5)
print(random_vec)

#Replacing maximum number in every row of the array with zero
random_vec = np.where(np.isin(random_vec, random_vec.max(axis=1)), 0, random_vec)
print(random_vec)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
[[ 1.  2.  3.  4.  0.]
 [ 6.  7.  8.  9.  0.]
 [11. 12. 13. 14.  0.]
 [16. 17. 18. 19.  0.]]
